// Generated by CoffeeScript 1.7.1
var YdnDbQuery;

YdnDbQuery = function() {
  this.$get = [
    function() {
      var Ydn;
      Ydn = function() {};
      Ydn.prototype.$find = function() {
        return console.log('ydn $find');
      };
      Ydn.prototype.$create = function() {
        return console.log('ydn $create');
      };
      Ydn.prototype.$update = function() {
        return console.log('ydn $update');
      };
      Ydn.prototype.$delete = function() {
        return console.log('ydn $delete');
      };
      return Ydn;
    }
  ];
};

angular.module('fm.player.model').provider('fm.player.model.YdnDbQuery', YdnDbQuery);
