// Generated by CoffeeScript 1.7.1
var DbQuery;

DbQuery = function() {
  var queryInterface;
  queryInterface = null;
  this.setDbQueryInterface = function(queryInterface) {
    if (queryInterface == null) {
      queryInterface = queryInterface;
    }
  };
  this.$get = [
    'fm.player.model.DbQueryInterface', function(DbQueryInterface) {
      return {
        queryInterface: queryInterface || DbQueryInterface
      };
    }
  ];
};

angular.module('fm.player.model').provider('fm.player.model.DbQuery', DbQuery);
