// Generated by CoffeeScript 1.7.1
var DbQueryInterface;

DbQueryInterface = function() {
  return {
    $find: function() {
      throw Error("Unimplemented method DbQueryInterface.$get().");
    },
    $create: function() {
      throw Error("Unimplemented method DbQueryInterface.$save().");
    },
    $update: function() {
      throw Error("Unimplemented method DbQueryInterface.$update().");
    },
    $delete: function() {
      throw Error("Unimplemented method DbQueryInterface.$delete().");
    },
    $count: function() {
      throw Error("Unimplemented method DbQueryInterface.$count().");
    }
  };
};

angular.module('fm.player.model').factory('fm.player.model.DbQueryInterface', DbQueryInterface);
