// Generated by CoffeeScript 1.7.1

/*
Post Model
 */
var PostModel,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

PostModel = function() {
  this.$get = [
    "fm.player.model", function(Model) {
      PostModel = (function(_super) {
        __extends(PostModel, _super);

        function PostModel() {
          return PostModel.__super__.constructor.apply(this, arguments);
        }

        return PostModel;

      })(Model);
      return new PostModel;
    }
  ];
};

angular.module('app').provider("PostModel", PostModel);
