# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6fa8afe64ca83d2f1dc44f792578e11d45d9a3f2d023f7cafc33e060d8da1d9e76a2d90d361d3b54bc408a1ee57e0664cf6321d0877ca501f2d9609fff593e8

test:
  secret_key_base: b37a87206242379c693502efdbf9f438eeaab8194a35c373e881caf5609a261a5cab248ad58f6bc8b3b42511806c29a9323c6f4ec81b37924e4f2b0a3147f38c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
