// Generated by CoffeeScript 1.7.1
var Model,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Model = function() {
  this.$get = [
    "fm.player.model.Base", function(BaseClassModel) {
      return Model = (function(_super) {
        __extends(Model, _super);

        function Model() {
          Model.__super__.constructor.call(this, null);
        }

        return Model;

      })(BaseClassModel);
    }
  ];
};

angular.module("fm.player.model", []).provider("fm.player.model", Model);
