// Generated by CoffeeScript 1.7.1
var Database;

Database = function() {
  var name, version;
  name = 'FmPlayerDbTemp';
  version = '1.0';
  this.setName = function(db_name) {
    if (db_name) {
      return name = db_name;
    }
  };
  this.setVersion = function(db_version) {
    if (db_version) {
      return version = db_version;
    }
  };
  this.$get = [
    function() {
      return {
        name: name,
        version: version
      };
    }
  ];
};

angular.module('fm.player.model').provider('fm.player.model.Database', Database);
