// Generated by CoffeeScript 1.7.1

/*
App Controller
 */
var AppCtrl, Config, Run;

AppCtrl = function($scope, Post) {
  return console.log("AppCtrl Post: ", Post);
};

AppCtrl.$inject = ['$scope', 'PostModel'];


/*
Module Config
 */

Config = function(DatabaseProvider, DbQueryProvider, YdnDbQueryProvider) {
  console.log('DatabaseProvider: ', DatabaseProvider);
  DatabaseProvider.setName('FmPlayerChrome');
  return DatabaseProvider.setVersion('1.0');
};

Config.$inject = ['fm.player.model.DatabaseProvider', 'fm.player.model.DbQueryProvider', 'fm.player.model.YdnDbQueryProvider'];


/*
Module Run
 */

Run = function(db, dbquery) {
  return console.log('db: ', db, dbquery.name);
};

Run.$inject = ['fm.player.model.Database', 'fm.player.model.DbQuery'];


/*
App
 */

angular.module("app", ["ngRoute", "fm.player.model"]).config(Config).run(Run).controller("AppCtrl", AppCtrl);
